import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:json_annotation/json_annotation.dart';

part 'entity_document.g.dart'; // This file will be generated by build_runner

@JsonSerializable()
class EntityDocument {
  final String id;
  final String name;
  final String category;
  final String description;
  final String fileUrl;
  final String dateTimeUploaded;
  final String size;
  final String type;
  final String fileExtension;
  final String fileThumbnailUrl;

  EntityDocument({
    required this.id,
    this.name = '',
    this.category = '',
    this.description = '',
    this.fileUrl = '',
    this.dateTimeUploaded = '',
    this.size = '',
    this.type = '',
    this.fileExtension = '',
    this.fileThumbnailUrl = '',
  });

  factory EntityDocument.fromFirestore(DocumentSnapshot doc) {
    Map<String, dynamic> data = doc.data() as Map<String, dynamic>;
    return EntityDocument.fromJson({
      ...data,
      'id': doc.id,
    });
  }

  factory EntityDocument.fromJson(Map<String, dynamic> json) =>
      _$EntityDocumentFromJson(json);

  Map<String, dynamic> toJson() => _$EntityDocumentToJson(this);
}
