import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:json_annotation/json_annotation.dart';

part 'entity_item.g.dart'; // This file will be generated by build_runner

@JsonSerializable()
class EntityItem {
  final String id;
  final String name;
  final String category;
  final String description;
  final String lastChecked;
  final String installer;
  final String purchaseInfo;
  final String specifications;
  final String warranty;
  final String billOfMaterials;
  final double taskComplete;

  EntityItem({
    required this.id,
    this.name = '',
    this.category = '',
    this.description = '',
    this.lastChecked = '',
    this.installer = '',
    this.purchaseInfo = '',
    this.specifications = '',
    this.warranty = '',
    this.billOfMaterials = '',
    this.taskComplete = 1.0,
  });

  factory EntityItem.fromFirestore(DocumentSnapshot doc) {
    Map<String, dynamic> data = doc.data() as Map<String, dynamic>;
    return EntityItem.fromJson({
      ...data,
      'id': doc.id,
    });
  }

  factory EntityItem.fromJson(Map<String, dynamic> json) =>
      _$EntityItemFromJson(json);

  Map<String, dynamic> toJson() => _$EntityItemToJson(this);
}
