// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZfKzXLPmOVbvqFT4iNEPV8JWUCfSFPjk',
    appId: '1:892922730613:web:e449afdbb040e21760c03c',
    messagingSenderId: '892922730613',
    projectId: 'captainapp-crew-2024',
    authDomain: 'captainapp-crew-2024.firebaseapp.com',
    storageBucket: 'captainapp-crew-2024.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy0ZzhFH_ueUCMAs-RjCpAX0I_3UJaXbg',
    appId: '1:892922730613:android:7e3025578951248360c03c',
    messagingSenderId: '892922730613',
    projectId: 'captainapp-crew-2024',
    storageBucket: 'captainapp-crew-2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4tfNSap63nk8q78RPv29xcRP-fb_jW2g',
    appId: '1:892922730613:ios:ab6eeb4e757a33d760c03c',
    messagingSenderId: '892922730613',
    projectId: 'captainapp-crew-2024',
    storageBucket: 'captainapp-crew-2024.appspot.com',
    iosBundleId: 'com.captainapp.crewDashboard',
  );
}
